---
title: "PROYECTO PRUEBA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


SUBIMOS LAS BASES DE DATOS

```{r}
Vidal<-read.csv("mariuvidal_timeline_database.csv", encoding = "UTF-8")
Alberto<-read.csv("alferdez_timeline_database.csv", encoding = "UTF-8")
read.csv("Solanopo_timeline_database.csv", encoding = "UTF-8")->Solano
```

Unir base de datos

```{r}
BASE_COMPLETA <-merge(x=ALBERTO, y=BASE_DE_DATOS_SOLANO, all = TRUE)
BASE_COMPLETA <- merge(x= BASE_COMPLETA, y=MARU_VIDAL, all = TRUE)

```
Cambiar formato a fecha

```{r}
BASE_COMPLETA$created_at <- as.Date(BASE_COMPLETA$created_at)

str(BASE_COMPLETA)
```
dividimos la columna de fecha en a単os, meses y dias.

```{r}
BASE_COMPLETA <- BASE_COMPLETA%>%mutate(A単o=substr(created_at, 1, 4),
                       Mes=substr(created_at, 6,7))
```
filtramos la base de datos 

```{r}
BASE_COMPLETA_FILTRADA <- filter(BASE_COMPLETA, A単o >= 2020)
```
renombramos algunas variables de la base de datos

```{r}
BASE_COMPLETA <- rename(BASE_COMPLETA, fecha = created_at, nombre = name, enviado_desde = source, tweet = text, likes = favorite_count)
```
volvemos a filtrar la base de datos por fecha para que quede mas comoda

```{r}
BASE_COMPLETA_FILTRADA2 <- filter(BASE_COMPLETA, A単o == "2021", Mes == "05")
```
